src/component/assets/_login.scss
로그인.scss의 잘못된 변수 이름 수정
resolves #48
=> refactor: 변수 이름 수정:

src/component/assets/_header.scss, src/component/assets/_login.scss, src/component/header/header.js
- header.js 수정
- login.scss 수정
- header.js 수정
resolves #{이슈번호}
=> fect : 파일 수정

README.md
=> refactor : lib 추가

src/component/assets/_mixins.scss
=> refactor : mixin 수정

README.md, src/component/assets/_inputs.scss
**input 컴포넌트 수정**
- input width 값 수정
resolves #61
=> refactor: input width 값 수정

src/component/assets/_recentproduct.scss, src/component/recent-product/index.html
- 클래스명 수정
- button클래스에서 recent-product__button로 클래스명 변경
resolves #70
=> refactor : class명 수정

README.md, src/component/assets/_recentproduct.scss, src/component/recent-product/assets/below.svg, src/component/recent-product/assets/upper.svg, src/component/recent-product/index.html, src/styles/style.scss
recentproduct 파일 복구
resolves #30
=> feat : recentproduct 복구

README.md, src/api/getPbImageURL.js, src/api/pocketbase.js
- getPbImageURL API 생성
- pocketbase api 생성
데이테베이스 이미지 가져올때 URL을 요청하여 액세스하는 API 생성
데이터베이스 불러오는 API 생성
resolves #85
=> feat : 데이터베이스 관련 API 생성

src/api/getPbImageURL.js
- getPbImageURL 함수 수정
resolves #87
=> feat : getPbImageURL 수정

src/component/assets/_popup.scss, src/component/pop-up/index.html, src/component/recent-product/index.html
- 절대경로로 수정
빌드관련 경로 수정 
resolves #{이슈번호}
=> refactor : 경로 수정

README.md, src/component/assets/_products-detail.scss, src/component/assets/_variables.scss, src/component/product/product-detail.html
- 클래스 없이 태그만 작성한 제품 상세 페이지 하단부 마크업에 클래스 부여
- 제품 상세 페이지 하단부 중 네비게이션 부분 스타일링 추가
resolves #96
=> feat: 제품 세부 정보 하단 마크업과 스타일링

package-lock.json, package.json, src/component/assets/_badges.scss, src/component/assets/_character.scss, src/component/assets/_footer.scss, src/component/assets/_header.scss, src/component/assets/_mixins.scss, src/component/assets/_product-slide.scss, src/component/assets/_products.scss, src/component/assets/img/next-button-black.svg, src/component/footer/footer.js, src/component/header/header.js, src/component/product/product-slide.html, src/component/product/product-slide.js, src/component/product/product.html, src/styles/style.scss, vite.config.js.timestamp-1720514974785-1cdf0bd91d479.mjs
- feat : font mixin 추가
- refactor : badges.scss
- refactor : badges.scss
- character.scss 불필요한 scss 삭제
- vite top-level-await 삭제
resolves #91
=> feat : product slide swiper 구현

src/component/assets/_cart.scss, src/component/assets/_typography.scss
- cart.scss 생성
- 장바구니 기본 스타일링
- typography 수정
장바구니 기본 스타일링
resolves #115
=> feat : 장바구니 기본 스타일링

src/component/assets/_buttons.scss, src/component/assets/_register.scss, src/component/assets/_reset.scss, src/pages/register/index.html, src/styles/style.scss
=> feat: 회원가입 스타일링 디테일

src/component/assets/_recentproduct.scss, src/component/recent-product/index.html, src/component/recent-product/main.js
- 같은 상품 클릭시 로컬스토리지에 저장 안하는 조건추가
- 상품 3개 이상 저장시 버튼 색상변경
- 최근 본 상품이 동일한 상품일 경우 로컬스토리지에 저장하지 않는 조건을 추가했습니다
- 최근 본 상품이 3개 이상인 경우 위아래 버튼이 활성화(색상변경)이 되도록 하였습니다
resolves #136
=> feat : 버튼 활성화 및 기능 추가

src/component/assets/_header.scss, src/component/header/header.html, src/component/header/header.js, src/component/product/product-slide.js, src/component/product/product.html
- header, product-slide 수정
resolves #141
=> feat :header, product-slide 수정

README.md, public/images/icon-arrow.svg, src/component/assets/_buttons.scss, src/component/assets/_forms.scss, src/component/assets/_inputs.scss, src/component/assets/_register.scss, src/component/assets/_reset.scss, src/component/assets/_typography.scss, src/pages/register/checkAll.js, src/pages/register/index.html, src/pages/register/register.js, src/pages/register/userAddress.js
** 기능 추가**
- input 경로 수정
- checkAll 함수 클래스 함수로 변경
- register/index.html: 아이디 빈값 삭제
- register 포켓베이스 데이터 연결 (함수 분리 필요)
- 주소 API 추가
- 핸드폰 번호 유효성 검사
- 이메일 검사
- 회원가입 페이지 스타일링 수정
resolves #34
resolves #36 
resolves #37
=> feat: 회원가입 스타일링 수정 및 기능 구현

README.md, src/component/assets/_products-detail.scss
- why 칼리 영역 마크업 마무리 함으로써 제품 상세 페이지 마크업 마무리 함
- why 칼리 영역 스타일 마무리 함으로써 제품 상세 페이지 스타일링 마무리 함 
- 7/10, 7/11 작업 내용 readme에 작성
resolves #132
=> feat: 제품 상세 페이지 마크업 및 스타일링 마무리

README.md, src/component/assets/_register.scss, src/pages/register/emailCheck.js, src/pages/register/idCheck.js, src/pages/register/index.html, src/pages/register/passwordCheck.js, src/pages/register/register.js
- src/pages/register/emailCheck.js: 이메일 체크 함수 분리
- src/pages/register/idCheck.js: 아이디 체크 함수 분리
- src/pages/register/passwordCheck.js: 비번 체크 함수 분리
- src/pages/register/index.html: 회원가입 페이지 컨테이너 클래스 추가
- src/pages/register/register.js: 함수 분리
- src/component/assets/_register.scss: 회원가입 스타일링
resolves #150
=> feat: 회원가입 기능 구현

index.html, src/component/assets/_cart.scss, src/pages/cart/index.html, src/pages/cart/main.js
- 전체선택 기능구현
- 위아래 체크박스 동기화 기능 구현
- `+`, `-` 버튼으로 수량변경 기능 구현
- 숫자 변경에 따른 금액변경 기능 구현
- 선택한 항목 선택삭제에 따른 삭제 기능 구현
- 로그인상태 장바구니 반영
- 전체선택박스 선택시 전체가 선택되는 기능구현 및 위아래 동일한 전체선택박스가 동기화 되도록하였습니다
- `+`, `-` 버튼으로 숫자변경 후 변경된 수량이 금액에도 반영하였습니다
-  선택삭제 버튼 클릭시 선택한 항목이 삭제됩니다 (로컬스토리지에 반영되는 기능 추가로 구현 필요)
-  로그인 후 고객 배송지 랜더링 및 주문하기 버튼 활성화
resolves #144
=> feat : 전체선택 체크박스 관련 기능구현

README.md, src/component/addShoppingBasket/addShoppingBasket.html, src/component/addShoppingBasket/addShoppingBasket.js, src/component/assets/_addShoppingBasket.scss
- 가격을 개수에 맞게 변동할 수 있도록 함
- 서버에서 상품 정보를 가져올 수 있도록 수정
- 클로저 함수를 이용해서 장바구니 추가 함수와 팝업 오픈 함수 수정
- 배지 추가와 그를 위한 마크업 변경과 스타일링 변경
- 장바구니 버튼 추가 기능 추가하여 사용자가 선택한 제품의 아이디와 개수를 로컬에 저장
resolves #102
=> feat: 장바구니 추가 기능 구현 마무리

src/component/addShoppingBasket/addShoppingBasket.js
- 기존 코드는 새항목 추가 시 새로운 내용으로 변경됨
- 새 항목일 시 새로운 것으로 받을 수 있도록 변경
기존 코드에서는 새항목이 추가되는 것이 아닌 새 항목으로 변경되었는데 이것을 새항목으로 추가될 수 있도록 변경
resolves #154
=> feat: 장바구니 추가 새 항목 추가 시 추가되도록 변경

src/pages/register/index.html
=> bug: API 미작동 이슈 수정

src/component/accodion/accodion.js, src/component/assets/_accodion.scss
- 클래스 이름 중복에 따른 스타일 붕괴로 클래스 이름 수정
- 그에 따른 js 내 스타일 이름 변경
- 클래스 중복으로 인해 스타일이 무너져 클래스 이름 수정
resolves #173
=> refactor: 아코디언 선택 클래스 수정

src/component/assets/_cart.scss, src/component/assets/_register.scss, src/pages/register/index.html, src/pages/register/register.js
- 회원가입 페이지에 푸터와 헤더를 합쳤습니다
- 장바구니 뱃지 및 일부 스타일링 수정
resolves #176
=> feat : 회원가입 페이지 합치기

src/component/assets/_product-list.scss, src/component/assets/_products.scss, src/pages/productList/index.html, src/pages/productList/productList.js, src/styles/style.scss
- 상품 리스트 페이지 초기 마크업
- 상품 리스트 페이지 초기 스타일링
- 상품 데이터 DB에서 가져오기
- 상품 리스트 페이지 초기 마크업
- 상품 리스트 페이지 초기 스타일링
- 상품 데이터 DB에서 가져오기
resolves #175
=> feat: 상품 리스트 페이지 마크업 및 스타일링과 데이터 받아오기

public/images/icon-bubble-tail.svg, src/component/assets/_products-detail.scss, src/component/assets/_products.scss, src/component/banner/banner.js, src/component/pop-up/main.js, src/component/product/product-bubble.html, src/component/product/product-bubble.js, src/component/product/product-slide1.js, src/component/product/product-slide2.js, src/component/recent-product/main.js, src/pages/product/product-detail.html, src/pages/product/product-detail.js
장바구니 담기 버블 마크업 및 스크립트 작업
resolves #{이슈번호}
=> feat: 장바구니 담기 버블 마크업 및 스크립트 작업

src/component/assets/_product-list.scss, src/pages/productList/index.html, src/pages/productList/productList.js, vite.config.js
제품 상세 페이지 마크업 및 스타일링 페이지네이션 제외 마무리
resolves #183
=> feat: 제품 리스트 페이지 마크업 및 스타일링 마무리(페이지네이션 제외)

README.md, index.html, src/component/assets/_products.scss, src/component/pop-up/main.js, src/component/product/product-slide.js, src/component/product/product-slide2.js, src/component/recent-product/main.js, src/pages/product/product-detail.js
=> bug: 없는 변수 호출 오류로 인한 디버깅

README.md, src/component/assets/_cart.scss, src/pages/cart/countedItem.js, src/pages/cart/delete.js, src/pages/cart/index.html, src/pages/cart/main.js, src/pages/cart/sumAllPrice.js, src/pages/cart/updatePrice.js
선택수량 및 전체수량 반영 동기화 
클래명 변경 및 리팩토링 
resolves #194
=> feat : 선택수량 및 전체수량 반영 동기화

src/component/assets/_inputs.scss, src/component/assets/_register.scss, src/component/assets/_variables.scss, src/component/product/product-slide.js, src/pages/register/emailCheck.js, src/pages/register/idCheck.js, src/pages/register/index.html, src/pages/register/nameCheck.js, src/pages/register/passwordCheck.js, src/pages/register/register.js, src/pages/register/userAddress.js
- 디버깅
- 스타일링
- 회원가입 스크립트 리팩토링
resolves #197
=> feat: 회원가입 스타일링 수정 및 주소 기능 추가

README.md, src/component/accodion/accodion.js, src/component/accodion/countAccodionItems.js, src/component/assets/_product-list.scss, src/pages/productList/index.html, src/pages/productList/productList.js
- 상품 카테고리에 해당하는 상품의 수를 아코디언 메뉴에 보이도록 함
- 수를 보이게 하기 위한 일부 마크업 수정
- 어제 오늘(7/16~17일 01시 30분) 내용 정리
resolves #193
=> feat: 상품 리스트 js 기능 중 상품 개수 세는 함수 구현

index.html, src/component/assets/_header.scss, src/component/header/header.js
header signup-> register로 변경 및 코드 웹 표준 검사
resolves #199
=> feat : header signup-> register로 변경 및 코드 웹 표준 검사

src/component/product/product-slide.js
- product-slide 수정
- product-slide 수정
resolves #201
=> refactor : product-slide

src/component/accodion/countAccodionItems.js, src/component/assets/_product-list.scss, src/pages/productList/index.html, src/pages/productList/productList.js
- 상품 이미지 클릭 시 상세 페이지로 이동할 수 있도록 변경
- 페이지네이션 기능 추가
- 그를 위한 마크업 수정
resolves #202
=> feat: 상품 리스트 페이지네이션 기능 구현

README.md, index.html, main.js, src/component/assets/_footer.scss, src/component/assets/_header.scss, src/component/assets/_popup.scss, src/component/assets/_products.scss, src/component/assets/_topBanner.scss, src/component/product/product-slide.js, src/component/recent-product/main.js, src/component/topBanner/index.html, src/component/topBanner/topBanner.js, src/styles/style.scss
- product-slide 디버깅 완료
- recnet-product 5개이상 안보이게 설정
resolves #204
=> feat : product-slide.js/recent-product

src/component/assets/_badges.scss
=> feat: 뱃지 스타일 추가

src/component/assets/_header.scss, src/component/assets/_products.scss, src/component/cancel/cancel.js, src/component/cancel/index.html, src/component/header/header.js, src/component/product/product-slide.js
- product-slide 디버깅 및 기능개선
- 회원 탈퇴기능 구현
resolves #214
resolves #221
=> feat : product-slide 디버깅 및 기능개선

src/component/assets/_cart.scss, src/pages/cart/countedItem.js, src/pages/cart/delete.js, src/pages/cart/hidePrice.js, src/pages/cart/index.html, src/pages/cart/main.js
- 장바구니 타이틀 변경
- 전체수량 초기설정 디버깅 
- 로그인 상태 UI 반영 문제 개선
- 로그인 버튼 클릭시 로그인 페이지 이동 기능 추가
- 상품 이미지 alt값 추가
- 할인율 0인 경우 가격 UI 변경
resolves #211
=> feat : 장바구니 디버깅 및 기능 개선

README.md, src/component/addShoppingBasket/addShoppingBasket.js, src/component/assets/_addShoppingBasket.scss, src/component/assets/_product-list.scss, src/pages/productList/index.html, src/pages/productList/productList.js
- 장바구니 추가 팝업에 있는 가격이 할인가여도 원가로 나오던 것을 할인가가 있으면 할인가로 변경
- 상품 리스트와 장바구니 추가 팝업을 서로 연결
- 각각의 기능을 추가하기 위한 스타일링과 마크업 추가
resolves #218
=> feat: 장바구니 추가 팝업 일부 수정과 상품리스트와 팝업 서로 연결

src/pages/register/index.html, src/pages/register/register.js
=> feat: 회원가입 리로드 페이지 지정

README.md, src/component/assets/_badges.scss, src/component/assets/_cart.scss, src/pages/cart/countedItem.js, src/pages/cart/delete.js, src/pages/cart/hidePrice.js, src/pages/cart/index.html, src/pages/cart/selectAll.js, src/pages/cart/sumAllPrice.js
=> refactor : 장바구니 디버깅 및 리팩토링 

src/pages/register/index.html, src/pages/register/register.js
=> bug: 포켓베이스 API에서 axios로 변경

src/component/cancel/cancel.js, src/component/header/header.js, src/component/product/product-slide.js, src/pages/member/mypage.html, src/pages/member/mypage.js
- mypage 회원탈퇴 기능 구현
resolves #229
=> feat : 회원탈퇴 기능 구현

src/component/accodion/accodion.js, src/component/accodion/countAccodionItems.js, src/component/addShoppingBasket/addShoppingBasket.js, src/component/assets/_accodion.scss, src/component/assets/_addShoppingBasket.scss, src/component/assets/_login.scss, src/pages/login/index.html, src/pages/login/login.js, src/pages/productList/index.html, src/pages/productList/productList.js
- 주석 추가
- 로그인 실패 시 alert 후 리로드
- 상품 추가 팝업 숫자에 , 추가
- 상품 추가 팝업에서 로컬스토리지에 저장되는 정보 변경
resolves #232
=> feat: 페이지 타이틀 변경, 로그인 실패시 리로드, 로컬 저장 정보 변경 등

src/pages/product/productCount.js, src/pages/product/productDetail.js
=> refactor: console.log 제거

src/component/assets/_accodion.scss, src/component/assets/_product-list.scss, src/pages/productList/productList.js
- 상품 list 받아올때 이미지에 상품 이름 alt 추가
- 상품 list 받아올때 이미지에 상품 이름 alt 추가
resolves #239
=> refactor: 이미지 alt 추가

index.html, src/pages/product/addToCartBubble.js
=> bug: 버블 문제 해결

src/component/assets/_products-detail.scss, src/component/assets/_products.scss, src/pages/product/addToCartBubble.js, src/pages/product/product-detail.html, src/pages/product/productCount.js
=> bug: 버블 미노출 오류 해결

index.html, src/component/banner/banner.js
=> refactor: 배너 이미지 포켓베이스 함수 추가

src/component/assets/_header.scss, src/component/banner/banner.js, src/pages/register/index.html
=> refactor: 접근성 개선

src/component/assets/_cart.scss, src/pages/cart/main.js
- 페이지 로드시 아코디언 펼친상태로 보여지게끔 수정
페이지 로드시 아코디언 펼친상태로 수정
resolves #246
=> feat : 아코디언 펼치기

src/component/assets/_mypage.scss
=> refactor : 마이페이지 이미지 둥글게

src/component/addShoppingBasket/addShoppingBasket.js, src/pages/productList/productList.js
- 원래 코드로 복구
-에러 발생으로 인한 원래 코드로 복구
resolves #255
=> fix: 페이지 이동 시 장바구니 팝업 생성 불가로 인한 코드 복구

index.html, robots.txt, src/component/banner/banner.html, src/component/cancel/cancel.js, src/component/footer/footer.js, src/component/header/header.js, src/pages/cart/index.html, src/pages/login/index.html, src/pages/member/mypage.html, src/pages/product/product-detail.html, src/pages/productList/index.html, src/pages/register/index.html
- 메타 태그 추가
- 검색로봇 허용
- 링크 속성 추가
=> feat: SEO 개선

src/pages/cart/delete.js, src/pages/cart/main.js
- 각 카테고리에 해당 상품 없을시 해당 카테고리 UI 삭제하기
각 카테고리에 해당 상품 없을시 해당 카테고리 UI 삭제하기
resolves #258
=> feat : 카테고리 UI 삭제 기능 추가

src/component/assets/_cart.scss
배송지 아이콘 webp로 수정 
resolves #260
=> fix : 배송아이콘 이미지 webp로 수정

src/component/assets/_header.scss, src/component/assets/_products-slide.scss, src/component/header/header.js, src/component/product/product-slide.js
=> refactor : product slide

src/pages/cart/delete.js
- 장바구니에 삭제시 장바구니 카운터 감소
resolves #{이슈번호}
=> feat : 장바구니에 삭제시 장바구니 카운터 감소

src/component/assets/_mypage.scss, src/lib/dom/CustomSwiper.js, src/lib/dom/closeCartPopUp.js, src/lib/dom/openCartPopUp.js, src/lib/dom/recentProducts.js, src/lib/dom/renderProductItem.js, src/pages/register/index.html
=> feat: 퍼포먼스 개선

README.md
- 7/18일 작업내용 리드미에  작성
- 7/18일 작업내용 리드미에  작성
resolves #267
=> docs: 7/18일 작업내용 작성

README.md
=> docs : 리드미 추가

README.md, src/component/addShoppingBasket/addShoppingBasket.js
- 접근성을 위한 키보드로 팝업 접근시 바로 접근 가능하도록 변경
resolves #270
=> feat: 접근성을 위한 키보드로 팝업 접근시 바로 접근 가능하도록 변경

src/component/assets/_cart.scss, src/pages/cart/countedItem.js, src/pages/cart/delete.js, src/pages/cart/hidePrice.js, src/pages/cart/index.html, src/pages/cart/sumAllPrice.js, src/pages/cart/updatePrice.js
결제예정금액 3만원 이하인 경우 배송비 무료조건 추가금액 계산해서 띄우는 기능 추가
resolves #273
=> feat : 배송비 무료조건 추가

src/component/assets/_header.scss
- fix : header.scss 현재 주소 없을때 나오는 선 제거
=> fix : header.scss 현재 주소 없을때 나오는 선 제거
